services:
  naviradiomanager:
    image: ghcr.io/brunopiras/naviradiomanager:latest
    container_name: naviradiomanager
    ports:
      - "8501:8501"
    environment:
      - APP_LANG=IT #Only IT or EN
      - NAVIDROME_URL=http://YOUR_IP:4533
      - NAVIDROME_USER=YOUR_USER
      - NAVIDROME_PASS=YOUR_PASS
      - NAVIDROME_SALT=sasjhghaghjsgahjgsa
    #volumes:
    #  - /path/to/radio_web.py:/app/radio_web.py #Optional to developers
    #  - /path/to/lang.py:/app/lang.py #Optional to developers
    restart: always
