# lang.py
TRANSLATIONS = {
    "IT": {
        "title": "📻 Navidrome Radio Manager",
        "welcome": "👋 Benvenuto! Inserisci i parametri di ricerca nella sidebar.",
        "search_header": "🔍 Cerca Stazioni",
        "mode": "Modalità:",
        "name_label": "Nome della radio:",
        "country_sel": "Scegli nazione (Ufficiale):",
        "country_text": "Oppure scrivi manuale:",
        "btn_search": "Avvia Ricerca",
        "btn_home": "Torna alla Home",
        "results": "Risultati della ricerca:",
        "no_results": "Nessun risultato trovato. Riprova con altri termini.",
        "add_btn": "Aggiungi a Navidrome",
        "success": "✅ Radio aggiunta con successo!",
        "duplicate_warn": "⚠️ Radio già presente nel tuo database",
        "total_radios": "Tot. stazioni:",
        "bulk_no_results": "⚠️ Nessuna radio da aggiungere!",
        "bulk_start": "🚀 Avvio aggiunta di massa...",
        "bulk_skip": "⏩ Salto (già presente):",
        "bulk_process": "➕ Aggiunta in corso:",
        "bulk_done": "✅ Completato! Aggiunte: {added}, Saltate: {skipped}",
        "bulk_toast": "✅ Operazione riuscita! (+{added})",
        "btn_bulk_add": "➕ Aggiungi l'intera pagina a Navidrome",
        "btn_sort_top": "🔥 Top Voti",
        "btn_sort_low": "🧊 Meno Votate",
        "btn_delete": "🗑️ Rimuovi",
        "msg_deleted": "🗑️ Radio Rimossa!",
        "err_add": "❌ Errore nell'aggiunta (forse già presente?)",
        "err_vote": "❌ Errore durante il voto",
        "vote_success": "🗳️ Voto inviato! Grazie!",
    },
    "EN": {
        "title": "📻 Navidrome Radio Manager",
        "welcome": "👋 Welcome! Enter your search parameters in the sidebar.",
        "search_header": "🔍 Search Stations",
        "mode": "Mode:",
        "name_label": "Radio Name:",
        "country_sel": "Choose Country (Official):",
        "country_text": "Or type manually:",
        "btn_search": "Start Search",
        "btn_home": "Back to Home",
        "results": "Search Results:",
        "no_results": "No results found. Please try different terms.",
        "add_btn": "Add to Navidrome",
        "success": "✅ Radio added successfully!",
        "duplicate_warn": "⚠️ Radio already in your database",
        "total_radios": "Total Radios:",
        "bulk_no_results": "⚠️ No radios to add!",
        "bulk_start": "🚀 Starting bulk add...",
        "bulk_skip": "⏩ Skipping (already exists):",
        "bulk_process": "➕ Adding:",
        "bulk_done": "✅ Completed! Added: {added}, Skipped: {skipped}",
        "bulk_toast": "✅ Operation successful! (+{added})",
        "btn_bulk_add": "➕ Add entire page to Navidrome",
        "btn_sort_top": "🔥 Top Votes",
        "btn_sort_low": "🧊 Low Votes",
        "btn_delete": "🗑️ Delete",
        "msg_deleted": "🗑️ Station Deleted!",
        "err_add": "❌ Error adding station (maybe already exists?)",
        "err_vote": "❌ Error while voting",
        "vote_success": "🗳️ Vote sent! Thanks!",
    }
}